version: '3.8'

services:
  musetalk:
    build:
      context: .
      dockerfile: Dockerfile
    image: musetalk:latest
    container_name: musetalk_container
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./configs:/app/configs
    ports:
      - "7860:7860"
    stdin_open: true
    tty: true
    command: bash  # Override to keep container running
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]